package site

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strconv"
	"strings"
	"time"

	"github.com/touchelos/cairn/schema"
	"github.com/touchelos/cairn/yamlsub"
)

// header is the preamble of every generated site.yaml.
//
// It is addressed to the admin who has to correct the file, because that is the
// entire onboarding model (CLAUDE.md §6): discovery-first, with a human
// reviewing a generated artifact rather than filling in a form.
const header = `# cairn site profile.
#
# Generated by ` + "`cairn init`" + `, which probed this host and wrote down what it found.
# It is meant to be read, corrected, and committed to git — cairn guesses, and a
# guess an admin has not checked is not a site profile.
#
# Where a value is wrong, edit it. ` + "`cairn init`" + ` will not overwrite this file
# without --force, and will show you what it would change.
#
# Unknown keys are an error rather than being ignored, so a typo here fails
# loudly instead of silently reverting to whatever was probed.
`

// EncodeYAML renders a profile as the site.yaml an admin reviews.
//
// Deterministic by construction: field order is fixed by this function, lists
// are emitted in the order the probes canonicalized them, and there is no
// generation timestamp. A stamp would make every regeneration differ from the
// last, so `cairn init` could not tell a real change from a re-run — which is
// the one thing it has to do (§2.7).
func (p Profile) EncodeYAML() ([]byte, error) {
	if p.Cluster == "" {
		return nil, fmt.Errorf("site: profile has no cluster name")
	}
	root := yamlsub.Map()

	root.SetRaw("version", "Format version of this file, not cairn's event schema.",
		strconv.Itoa(orDefault(p.Version, ProfileVersion)))
	root.Set("cluster",
		"The name stamped on every event collected here. Two clusters sharing a\n"+
			"name make two sites' bundles look like one site's, so make it unique.",
		string(p.Cluster))

	sched := yamlsub.Map()
	sched.Set("kind", "", p.Scheduler.Kind)
	sched.Set("version", "", p.Scheduler.Version)
	sched.Set("config_path", "", p.Scheduler.ConfigPath)
	sched.SetList("partitions", "", p.Scheduler.Partitions)
	sched.SetList("qos", "", p.Scheduler.QOS)
	root.SetNode("scheduler",
		"The batch system. This is the single most load-bearing value in the file:\n"+
			"it is what stops a model answering a Slurm question with PBS syntax.",
		sched)

	mods := yamlsub.Map()
	mods.Set("kind", "", p.Modules.Kind)
	mods.SetList("roots", "", p.Modules.Roots)
	root.SetNode("modules",
		"Environment modules. Needed to answer \"why can't I load this module\"\n"+
			"against what this site actually publishes.", mods)

	if len(p.Builders) > 0 {
		bs := yamlsub.Seq()
		for _, b := range p.Builders {
			m := yamlsub.Map()
			m.Set("kind", "", b.Kind)
			m.Set("root", "", b.Root)
			bs.Append(m)
		}
		root.SetNode("builders", "Spack and EasyBuild installation roots.", bs)
	}

	osn := yamlsub.Map()
	osn.Set("id", "", p.OS.ID)
	osn.Set("version_id", "", p.OS.VersionID)
	osn.Set("kernel_release", "", p.OS.KernelRelease)
	osn.Set("glibc_version", "", p.OS.GlibcVersion)
	root.SetNode("os", "Base system. Drift in these is invisible until jobs die.", osn)

	fab := yamlsub.Map()
	fab.Set("kind", "", p.Fabric.Kind)
	fab.SetList("hcas", "", p.Fabric.HCAs)
	fab.SetList("rates", "", p.Fabric.Rates)
	root.SetNode("fabric", "High-speed interconnect.", fab)

	gpu := yamlsub.Map()
	gpu.Set("vendor", "", p.GPU.Vendor)
	gpu.Set("driver_version", "", p.GPU.DriverVersion)
	gpu.Set("cuda_version", "", p.GPU.CUDAVersion)
	gpu.SetList("models", "", p.GPU.Models)
	if p.GPU.Vendor != "" {
		gpu.SetRaw("dcgm", "", strconv.FormatBool(p.GPU.DCGM))
	}
	root.SetNode("gpu", "Accelerators.", gpu)

	if len(p.Mounts) > 0 {
		ms := yamlsub.Seq()
		for _, m := range p.Mounts {
			n := yamlsub.Map()
			n.Set("mountpoint", "", m.Mountpoint)
			n.Set("fstype", "", m.FSType)
			n.Set("source", "", m.Source)
			ms.Append(n)
		}
		root.SetNode("mounts",
			"Shared filesystems. The root filesystem and other node-local mounts are\n"+
				"omitted: what matters is what a submission script can reference.", ms)
	}

	bmc := yamlsub.Map()
	bmc.Set("kind", "", p.BMC.Kind)
	if p.BMC.Kind != "" && p.BMC.Kind != "none" {
		bmc.SetRaw("reachable", "", strconv.FormatBool(p.BMC.Reachable))
	}
	root.SetNode("bmc", "Out-of-band management.", bmc)

	if len(p.Metrics) > 0 {
		ms := yamlsub.Seq()
		for _, m := range p.Metrics {
			n := yamlsub.Map()
			n.Set("kind", "", m.Kind)
			n.Set("endpoint", "", m.Endpoint)
			ms.Append(n)
		}
		root.SetNode("metrics",
			"Telemetry already deployed here. cairn reads from these where present\n"+
				"rather than asking anyone to replace them.", ms)
	}

	// Only the probes that found nothing are written down.
	//
	// A probe that succeeded has already said what it found, in the sections
	// above — repeating it here would double the length of a file whose whole
	// purpose is to be read. What cannot be inferred from the sections above is
	// the difference between "there is no GPU stack here" and "cairn never
	// managed to look", and that is exactly what these entries record.
	if gaps := p.Missing(); len(gaps) > 0 {
		ps := yamlsub.Seq()
		for _, pr := range gaps {
			n := yamlsub.Map()
			n.Set("name", "", pr.Name)
			n.Set("level", "", pr.Level.String())
			n.Set("detail", "", pr.Detail)
			ps.Append(n)
		}
		root.SetNode("gaps",
			"What cairn looked for and did not find.\n"+
				"\n"+
				"Usually correct — a CPU-only site has no GPU stack, and a tenant node has\n"+
				"no BMC. Recorded so that a thin profile reads as an incompletely probed\n"+
				"one rather than a simple site, because those need opposite responses.\n"+
				"\n"+
				"Anything here that you know to be present, cairn could not reach. Fill in\n"+
				"the section above by hand and delete the entry.", ps)
	}

	var b strings.Builder
	b.WriteString(header)
	b.WriteString("\n")
	b.WriteString(root.Render())
	return []byte(b.String()), nil
}

func orDefault(v, def int) int {
	if v == 0 {
		return def
	}
	return v
}

// DecodeYAML parses a site.yaml.
//
// Every unknown key is collected and reported together rather than failing on
// the first: an admin correcting a file wants the whole list, not one error per
// edit-and-rerun cycle.
func DecodeYAML(data []byte) (Profile, error) {
	root, err := yamlsub.Parse(data)
	if err != nil {
		return Profile{}, fmt.Errorf("site.yaml: %w", err)
	}
	if !root.IsMap() {
		return Profile{}, fmt.Errorf("site.yaml: expected a mapping at the top level")
	}

	r := yamlsub.NewReader(root, "")
	var p Profile
	p.Version = r.IntOr("version", ProfileVersion)
	p.Cluster = schema.ClusterName(r.Str("cluster"))

	sched := r.Sub("scheduler")
	p.Scheduler = Scheduler{
		Kind:       sched.Str("kind"),
		Version:    sched.Str("version"),
		ConfigPath: sched.Str("config_path"),
		Partitions: sched.List("partitions"),
		QOS:        sched.List("qos"),
	}

	mods := r.Sub("modules")
	p.Modules = Modules{Kind: mods.Str("kind"), Roots: mods.List("roots")}

	var builderReaders []*yamlsub.Reader
	for _, br := range r.Each("builders") {
		p.Builders = append(p.Builders, Builder{Kind: br.Str("kind"), Root: br.Str("root")})
		builderReaders = append(builderReaders, br)
	}

	osr := r.Sub("os")
	p.OS = OSFacts{
		ID:            osr.Str("id"),
		VersionID:     osr.Str("version_id"),
		KernelRelease: osr.Str("kernel_release"),
		GlibcVersion:  osr.Str("glibc_version"),
	}

	fab := r.Sub("fabric")
	p.Fabric = Fabric{Kind: fab.Str("kind"), HCAs: fab.List("hcas"), Rates: fab.List("rates")}

	gpu := r.Sub("gpu")
	p.GPU = GPUFacts{
		Vendor:        gpu.Str("vendor"),
		DriverVersion: gpu.Str("driver_version"),
		CUDAVersion:   gpu.Str("cuda_version"),
		Models:        gpu.List("models"),
		DCGM:          gpu.Bool("dcgm"),
	}

	var mountReaders []*yamlsub.Reader
	for _, mr := range r.Each("mounts") {
		p.Mounts = append(p.Mounts, Mount{
			Mountpoint: mr.Str("mountpoint"),
			FSType:     mr.Str("fstype"),
			Source:     mr.Str("source"),
		})
		mountReaders = append(mountReaders, mr)
	}

	bmc := r.Sub("bmc")
	p.BMC = BMCFacts{Kind: bmc.Str("kind"), Reachable: bmc.Bool("reachable")}

	var metricReaders []*yamlsub.Reader
	for _, mr := range r.Each("metrics") {
		p.Metrics = append(p.Metrics, MetricsSystem{Kind: mr.Str("kind"), Endpoint: mr.Str("endpoint")})
		metricReaders = append(metricReaders, mr)
	}

	// Only gaps are stored, so everything read back is an unavailable probe.
	// Reveals is not stored — it is static text belonging to the probe, not a
	// fact about this site — so a decoded profile carries the record of the gap
	// without the explanation, which is all any consumer of a stored profile
	// needs.
	var probeReaders []*yamlsub.Reader
	for _, pr := range r.Each("gaps") {
		level := LevelUnprivileged
		if pr.Str("level") == "privileged" {
			level = LevelPrivileged
		}
		p.Probes = append(p.Probes, Probe{
			Name:      pr.Str("name"),
			Level:     level,
			Available: false,
			Detail:    pr.Str("detail"),
		})
		probeReaders = append(probeReaders, pr)
	}

	all := []*yamlsub.Reader{r, sched, mods, osr, fab, gpu, bmc}
	all = append(all, builderReaders...)
	all = append(all, mountReaders...)
	all = append(all, metricReaders...)
	all = append(all, probeReaders...)

	if errs := yamlsub.CollectErrors(all...); len(errs) > 0 {
		return Profile{}, fmt.Errorf("site.yaml:\n  %s", strings.Join(errs, "\n  "))
	}
	if p.Cluster == "" {
		return Profile{}, fmt.Errorf("site.yaml: `cluster` is required")
	}
	if p.Version != ProfileVersion {
		return Profile{}, fmt.Errorf(
			"site.yaml: profile version %d, but this cairn understands version %d",
			p.Version, ProfileVersion)
	}
	return p, nil
}

// ---------- node profiles ----------

// EncodeJSON renders a node profile in canonical form.
//
// JSON rather than YAML, and the asymmetry is deliberate. site.yaml is read and
// corrected by a person, so it earns comments and a hand-rolled emitter. A node
// profile is machine-written on a compute node, piped through whatever fan-out
// the site already runs, and compared — never edited. It wants the format that
// survives a pipe intact.
func (n NodeProfile) EncodeJSON() ([]byte, error) {
	if n.Cluster == "" {
		return nil, fmt.Errorf("site: node profile has no cluster name")
	}
	if n.Node == "" {
		return nil, fmt.Errorf("site: node profile has no node name")
	}
	var b strings.Builder
	b.WriteString(`{"profile_version":`)
	b.WriteString(strconv.Itoa(orDefault(n.Version, ProfileVersion)))
	b.WriteString(`,"cluster":`)
	b.WriteString(strconv.Quote(string(n.Cluster)))
	b.WriteString(`,"node":`)
	b.WriteString(strconv.Quote(string(n.Node)))
	b.WriteString(`,"captured_at":`)
	b.WriteString(strconv.Quote(schema.FormatTime(n.CapturedAt)))
	b.WriteString(`,"keys":{`)
	for i, k := range n.SortedKeys() {
		if i > 0 {
			b.WriteByte(',')
		}
		b.WriteString(strconv.Quote(k))
		b.WriteByte(':')
		b.WriteString(strconv.Quote(n.Keys[k]))
	}
	b.WriteString(`},"probes":[`)
	for i, pr := range n.Probes {
		if i > 0 {
			b.WriteByte(',')
		}
		fmt.Fprintf(&b, `{"name":%s,"level":%s,"available":%s,"detail":%s,"reveals":%s}`,
			strconv.Quote(pr.Name), strconv.Quote(pr.Level.String()),
			strconv.FormatBool(pr.Available), strconv.Quote(pr.Detail), strconv.Quote(pr.Reveals))
	}
	b.WriteString("]}\n")
	return []byte(b.String()), nil
}

// DecodeNodeJSON parses a node profile.
//
// The writer above is hand-rolled for canonical byte order, exactly as
// schema/encode.go is; the reader uses encoding/json with DisallowUnknownFields,
// exactly as schema/decode.go does. Both are stdlib, so the no-third-party guard
// is satisfied either way, and matching the existing split keeps one convention
// in the repo rather than two.
//
// Unknown fields are rejected for the same reason they are there: a profile
// written by a newer cairn must fail loudly rather than be compared with half
// its drift keys silently dropped.
func DecodeNodeJSON(data []byte) (NodeProfile, error) {
	var raw struct {
		Version    int               `json:"profile_version"`
		Cluster    string            `json:"cluster"`
		Node       string            `json:"node"`
		CapturedAt string            `json:"captured_at"`
		Keys       map[string]string `json:"keys"`
		Probes     []struct {
			Name      string `json:"name"`
			Level     string `json:"level"`
			Available bool   `json:"available"`
			Detail    string `json:"detail"`
			Reveals   string `json:"reveals"`
		} `json:"probes"`
	}
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&raw); err != nil {
		return NodeProfile{}, fmt.Errorf("node profile: %w", err)
	}
	if raw.Cluster == "" || raw.Node == "" {
		return NodeProfile{}, fmt.Errorf("node profile: cluster and node are both required")
	}
	if raw.Version != ProfileVersion {
		return NodeProfile{}, fmt.Errorf(
			"node profile for %s: version %d, but this cairn understands version %d",
			raw.Node, raw.Version, ProfileVersion)
	}
	var at time.Time
	if raw.CapturedAt != "" {
		t, err := schema.ParseTime(raw.CapturedAt)
		if err != nil {
			return NodeProfile{}, fmt.Errorf("node profile for %s: captured_at: %w", raw.Node, err)
		}
		at = t
	}
	np := NodeProfile{
		Version:    raw.Version,
		Cluster:    schema.ClusterName(raw.Cluster),
		Node:       schema.Hostname(raw.Node),
		CapturedAt: at,
		Keys:       raw.Keys,
	}
	if np.Keys == nil {
		np.Keys = map[string]string{}
	}
	for _, pr := range raw.Probes {
		level := LevelUnprivileged
		if pr.Level == "privileged" {
			level = LevelPrivileged
		}
		np.Probes = append(np.Probes, Probe{
			Name: pr.Name, Level: level, Available: pr.Available,
			Detail: pr.Detail, Reveals: pr.Reveals,
		})
	}
	return np, nil
}
